export const ResMsg = {
    auth: {
        SUCCESS: "Logged in successfully",
        BLOCKED: "Your account has been blocked.!!'",
        MOBILE_ADDED: "Mobile number has been added successfully..!!"
    },
    user: {
        USER_NOT_FOUND: "User not found in records",
        OTP_UNMATCHED: "OTP do not matched",
        OTP_SENT: "OTP has send as requested",
        USER_NAME_IS_ALREADY_IN_USE: "Username is already in use.",
        EMAIL_VERIFIED: "Email has been verified successfully.",
        EMAIL_ALREADY_VERIFIED: "Email is already verified",
        MOBILE_ALREADY_VERIFIED: "Mobile is already verified",
        UPDATED_PROFILE: "Profile has been updated successfully",
        MOBILE_VERIFIED: "Mobile number has been verified successfully..!!",
        FETCHED_USER_DETAILS: "Fetched User Details."
    },
    follow: {
        FOLLOWED_USER: "You have followed to other user",
        UNFOLLOW_USER: "You have Un-followed this user",
        FOLLOWED_BACK: "You have successfully followed back",
        USER_ALREADY_FOLLOWED: "User has been followed already",
        FETCHED_FOLLOW_REQ_LIST: "Fetched list of followers request",
        USER_NOT_FOLLOWED: "User you are following back, had not followed you."
    },
    block: {
        BLOCK_ALREADY: "You have blocked already",
        UNBLOCK_USER: "You have unblocked this user",
        BLOCKED_USER: "You have block other user successfully",
        USER_BLOCKED: "User has been blocked by you.",
        USER_BLOCKED_BY_OTHER: 'You habe been blocked.',
        FETCHED_BLOCKED: "Fetched blocked users list",
        HAVE_NOT_BLOCKED: "You have not blocked this user to unblock"
    },
    errors: {
        INTERNAL_SERVER_ERROR: "Error,,!! Internal server error.",
        ALL_FIELDS_ARE_REQUIRED: "All fields are required",
        SOMETHING_WENT_WRONG: "Something went wrong.",
        FOLLOW_CANT_BE_A_SAME_USER: "Following id and user id can not be same" 
    }
}